/**
 * Validates the question bank and test forms, writes supabase/seed.sql and,
 * with --push, upserts everything into Supabase through seed_content().
 *
 *   npm run seed           # validate + write seed.sql
 *   npm run seed -- --push # also push to the database in .env.local
 */
import { existsSync, writeFileSync } from "node:fs";
import { english } from "../content/questions/english.ts";
import { math } from "../content/questions/math.ts";
import type { QuestionSeed, SubjectBank } from "../content/questions/schema.ts";
import { tests } from "../content/tests.ts";

const banks: SubjectBank[] = [english, math];
const byId = new Map<string, { subject: string; q: QuestionSeed }>();
const errors: string[] = [];

for (const bank of banks) {
  for (const q of bank.questions) {
    if (byId.has(q.id)) errors.push(`Duplicate question id ${q.id}`);
    byId.set(q.id, { subject: bank.subject, q });
    if (q.type !== "spr" && !["A", "B", "C", "D"].includes(q.answer)) {
      errors.push(`${q.id}: invalid answer ${q.answer}`);
    }
    if (q.type === "spr" && q.accepted.length === 0) errors.push(`${q.id}: no accepted answers`);
  }
}

for (const test of tests) {
  const seen = new Set<string>();
  for (const mod of test.modules) {
    for (const id of mod.questions) {
      const entry = byId.get(id);
      if (!entry) errors.push(`${test.id}: unknown question ${id}`);
      else if (entry.subject !== mod.subject) errors.push(`${test.id}: ${id} is not ${mod.subject}`);
      if (seen.has(id)) errors.push(`${test.id}: duplicate question ${id}`);
      seen.add(id);
    }
  }
}

if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

const questions = [...byId.values()].map(({ subject, q }) => {
  const isSpr = q.type === "spr";
  return {
    id: q.id,
    subject,
    domain: q.domain,
    skill: q.skill,
    difficulty: q.difficulty,
    type: isSpr ? "spr" : "mcq",
    stimulus: q.stimulus ?? [],
    prompt: q.prompt,
    choices: isSpr ? null : q.choices,
    answer: isSpr ? { value: q.value, accepted: q.accepted } : { choice: q.answer },
    explanation: q.explanation,
  };
});

const forms = tests.map((t) => ({
  id: t.id,
  section: t.section,
  title: t.title,
  description: t.description,
  sort: t.sort,
  modules: t.modules.map((m) => ({
    title: m.title,
    subject: m.subject,
    duration_seconds: m.minutes * 60,
    question_ids: m.questions,
  })),
}));

// A plain SQL copy, so the database can also be seeded from the SQL editor.
const TAG = "$seed$";
const quote = (value: unknown) => {
  const s = JSON.stringify(value);
  if (s.includes(TAG)) throw new Error(`Content contains reserved tag ${TAG}`);
  return `${TAG}${s}${TAG}::jsonb`;
};
writeFileSync(
  new URL("../supabase/seed.sql", import.meta.url),
  `-- Generated by scripts/seed.mts. Do not edit by hand.
-- Run in the Supabase SQL editor as the postgres role.

set local role postgres;

insert into public.questions (id, subject, domain, skill, difficulty, type, stimulus, prompt, choices, answer, explanation)
select id, subject, domain, skill, difficulty, type, stimulus, prompt, choices, answer, explanation
from jsonb_to_recordset(${quote(questions)}) as q(
  id text, subject public.subject, domain text, skill text, difficulty public.difficulty,
  type public.question_type, stimulus jsonb, prompt text, choices jsonb, answer jsonb, explanation text
)
on conflict (id) do update set
  subject = excluded.subject, domain = excluded.domain, skill = excluded.skill,
  difficulty = excluded.difficulty, type = excluded.type, stimulus = excluded.stimulus,
  prompt = excluded.prompt, choices = excluded.choices, answer = excluded.answer,
  explanation = excluded.explanation;

insert into public.test_forms (id, section, title, description, modules, sort)
select id, section, title, description, modules, sort
from jsonb_to_recordset(${quote(forms)}) as f(
  id text, section public.exam_section, title text, description text, modules jsonb, sort int
)
on conflict (id) do update set
  section = excluded.section, title = excluded.title, description = excluded.description,
  modules = excluded.modules, sort = excluded.sort;
`,
);

const letters: Record<string, number> = {};
for (const { q } of byId.values()) {
  if (q.type !== "spr") letters[q.answer] = (letters[q.answer] ?? 0) + 1;
}
console.log(`Validated ${questions.length} questions and ${forms.length} test forms.`);
console.log("Answer distribution:", letters);
for (const t of tests) {
  console.log(`  ${t.id}: ${t.modules.map((m) => `${m.questions.length}q/${m.minutes}m`).join(" + ")}`);
}

if (process.argv.includes("--push")) {
  if (existsSync(".env.local")) process.loadEnvFile(".env.local");
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  const secret = process.env.EXAM_SERVER_SECRET;
  if (!url || !key || !secret) {
    console.error("Missing NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY or EXAM_SERVER_SECRET.");
    process.exit(1);
  }

  const response = await fetch(`${url}/rest/v1/rpc/seed_content`, {
    method: "POST",
    headers: { apikey: key, "Content-Type": "application/json" },
    body: JSON.stringify({ p_secret: secret, p_questions: questions, p_forms: forms }),
  });
  const body = await response.text();
  if (!response.ok) {
    console.error(`Push failed (${response.status}): ${body}`);
    process.exit(1);
  }
  console.log("Pushed to Supabase:", body);
}
